package uk.co.platitech;
// Generated Nov 9, 2014 2:37:52 PM by Hibernate Tools 4.3.1


import javax.persistence.*;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * AccountBalance generated by hbm2java
 */
@Entity
@Table(name="account_balance"
    ,catalog="budget_app"
        , uniqueConstraints = @UniqueConstraint(columnNames="account")
)
public class AccountBalanceEntity  implements java.io.Serializable {


    private Integer id;
    private BankAccountEntity bankAccount;
    private Long balance;
    private Long lastBalance;

    public AccountBalanceEntity() {
    }


    public AccountBalanceEntity(BankAccountEntity bankAccount) {
        this.bankAccount = bankAccount;
    }
    public AccountBalanceEntity(BankAccountEntity bankAccount, Long balance, Long lastBalance) {
        this.bankAccount = bankAccount;
        this.balance = balance;
        this.lastBalance = lastBalance;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account", unique=true, nullable=false)
    public BankAccountEntity getBankAccount() {
        return this.bankAccount;
    }

    public void setBankAccount(BankAccountEntity bankAccount) {
        this.bankAccount = bankAccount;
    }


    @Column(name="balance")
    public Long getBalance() {
        return this.balance;
    }

    public void setBalance(Long balance) {
        this.balance = balance;
    }


    @Column(name="last_balance")
    public Long getLastBalance() {
        return this.lastBalance;
    }

    public void setLastBalance(Long lastBalance) {
        this.lastBalance = lastBalance;
    }





}


