package uk.co.platitech;
// Generated Nov 9, 2014 2:37:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountTransactions generated by hbm2java
 */
@Entity
@Table(name="account_transactions"
    ,catalog="budget_app"
)
public class AccountTransactionsEntity implements java.io.Serializable {


     private String transactionId;
     private BankAccountEntity bankAccountEntity;
     private TransactionCategoryEntity transactionCategory;
     private String transactionAmount;
     private String transactionDate;
     private String transactionName;

    public AccountTransactionsEntity() {
    }

	
    public AccountTransactionsEntity(String transactionId) {
        this.transactionId = transactionId;
    }
    public AccountTransactionsEntity(String transactionId, BankAccountEntity bankAccountEntity, TransactionCategoryEntity transactionCategoryEntity, String transactionAmount, String transactionDate, String transactionName) {
       this.transactionId = transactionId;
       this.bankAccountEntity = bankAccountEntity;
       this.transactionCategory = transactionCategoryEntity;
       this.transactionAmount = transactionAmount;
       this.transactionDate = transactionDate;
       this.transactionName = transactionName;
    }
   
     @Id 

    
    @Column(name="transaction_id", unique=true, nullable=false)
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account")
    public BankAccountEntity getBankAccountEntity() {
        return this.bankAccountEntity;
    }
    
    public void setBankAccountEntity(BankAccountEntity bankAccountEntity) {
        this.bankAccountEntity = bankAccountEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transaction_type")
    public TransactionCategoryEntity getTransactionCategory() {
        return this.transactionCategory;
    }
    
    public void setTransactionCategory(TransactionCategoryEntity transactionCategoryEntity) {
        this.transactionCategory = transactionCategoryEntity;
    }

    
    @Column(name="transaction_amount")
    public String getTransactionAmount() {
        return this.transactionAmount;
    }
    
    public void setTransactionAmount(String transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    
    @Column(name="transaction_date")
    public String getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="transaction_name")
    public String getTransactionName() {
        return this.transactionName;
    }
    
    public void setTransactionName(String transactionName) {
        this.transactionName = transactionName;
    }




}


