package uk.co.platitech;
// Generated Nov 9, 2014 2:37:52 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * AccountBalance generated by hbm2java
 */
@Entity
@Table(name="account_balance"
    ,catalog="budget_app"
)
public class AccountBalanceEntity  implements java.io.Serializable {


     private int account;
     private BankAccountEntity bankAccountEntity;
     private Long balance;
     private Long lastBalance;

    public AccountBalanceEntity() {
    }

	
    public AccountBalanceEntity(BankAccountEntity bankAccountEntity) {
        this.bankAccountEntity = bankAccountEntity;
    }
    public AccountBalanceEntity(BankAccountEntity bankAccountEntity, Long balance, Long lastBalance) {
       this.bankAccountEntity = bankAccountEntity;
       this.balance = balance;
       this.lastBalance = lastBalance;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="bankAccount"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="account", unique=true, nullable=false)
    public int getAccount() {
        return this.account;
    }
    
    public void setAccount(int account) {
        this.account = account;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public BankAccountEntity getBankAccountEntity() {
        return this.bankAccountEntity;
    }
    
    public void setBankAccountEntity(BankAccountEntity bankAccountEntity) {
        this.bankAccountEntity = bankAccountEntity;
    }

    
    @Column(name="balance")
    public Long getBalance() {
        return this.balance;
    }
    
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    
    @Column(name="last_balance")
    public Long getLastBalance() {
        return this.lastBalance;
    }
    
    public void setLastBalance(Long lastBalance) {
        this.lastBalance = lastBalance;
    }




}


