package uk.co.platitech;
// Generated 26-Nov-2014 12:12:14 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AccountBalance generated by hbm2java
 */
@Entity
@Table(name="account_balance"
    ,catalog="budget_app"
    , uniqueConstraints = @UniqueConstraint(columnNames="account") 
)
public class AccountBalanceEntity implements java.io.Serializable {


     private Integer id;
     private BankAccountEntity bankAccount;
     private Long balance;
     private Long lastBalance;

    public AccountBalanceEntity() {
    }

	
    public AccountBalanceEntity(BankAccountEntity bankAccount) {
        this.bankAccount = bankAccount;
    }
    public AccountBalanceEntity(BankAccountEntity bankAccount, Long balance, Long lastBalance) {
       this.bankAccount = bankAccount;
       this.balance = balance;
       this.lastBalance = lastBalance;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account", unique=true, nullable=false)
    public BankAccountEntity getBankAccount() {
        return this.bankAccount;
    }
    
    public void setBankAccount(BankAccountEntity bankAccount) {
        this.bankAccount = bankAccount;
    }

    
    @Column(name="balance")
    public Long getBalance() {
        return this.balance;
    }
    
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    
    @Column(name="last_balance")
    public Long getLastBalance() {
        return this.lastBalance;
    }
    
    public void setLastBalance(Long lastBalance) {
        this.lastBalance = lastBalance;
    }




}


