package uk.co.platitech;
// Generated Nov 9, 2014 2:37:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name="bank_account"
    ,catalog="budget_app"
)
public class BankAccountEntity implements java.io.Serializable {


     private Integer id;
     private CurrenciesEntity currenciesEntity;
     private UsersEntity users;
     private String accountName;
     private Integer accountNumber;
     private Set<AccountTransactionsEntity> accountTransactionseEntities = new HashSet<AccountTransactionsEntity>(0);
     private AccountBalanceEntity accountBalance;

    public BankAccountEntity() {
    }

	
    public BankAccountEntity(CurrenciesEntity currenciesEntity) {
        this.currenciesEntity = currenciesEntity;
    }
    public BankAccountEntity(CurrenciesEntity currenciesEntity, UsersEntity usersEntity, String accountName, Integer accountNumber, Set<AccountTransactionsEntity> accountTransactionseEntities, AccountBalanceEntity accountBalance) {
       this.currenciesEntity = currenciesEntity;
       this.users = usersEntity;
       this.accountName = accountName;
       this.accountNumber = accountNumber;
       this.accountTransactionseEntities = accountTransactionseEntities;
       this.accountBalance = accountBalance;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="currency", nullable=false)
    public CurrenciesEntity getCurrenciesEntity() {
        return this.currenciesEntity;
    }
    
    public void setCurrenciesEntity(CurrenciesEntity currenciesEntity) {
        this.currenciesEntity = currenciesEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id")
    public UsersEntity getUsers() {
        return this.users;
    }
    
    public void setUsers(UsersEntity usersEntity) {
        this.users = usersEntity;
    }

    
    @Column(name="account_name")
    public String getAccountName() {
        return this.accountName;
    }
    
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    
    @Column(name="account_number")
    public Integer getAccountNumber() {
        return this.accountNumber;
    }
    
    public void setAccountNumber(Integer accountNumber) {
        this.accountNumber = accountNumber;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy= "bankAccountEntity")
    public Set<AccountTransactionsEntity> getAccountTransactionseEntities() {
        return this.accountTransactionseEntities;
    }
    
    public void setAccountTransactionseEntities(Set<AccountTransactionsEntity> accountTransactionseEntities) {
        this.accountTransactionseEntities = accountTransactionseEntities;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy= "bankAccountEntity")
    public AccountBalanceEntity getAccountBalance() {
        return this.accountBalance;
    }
    
    public void setAccountBalance(AccountBalanceEntity accountBalance) {
        this.accountBalance = accountBalance;
    }




}


