package uk.co.platitech;
// Generated Nov 9, 2014 2:37:52 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Currencies generated by hbm2java
 */
@Entity
@Table(name="currencies"
    ,catalog="budget_app"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class CurrenciesEntity implements java.io.Serializable {


     private Integer id;
     private String code;
     private String country;
     private Set<BankAccountEntity> bankAccountEntities = new HashSet<BankAccountEntity>(0);

    public CurrenciesEntity() {
    }

	
    public CurrenciesEntity(String code, String country) {
        this.code = code;
        this.country = country;
    }
    public CurrenciesEntity(String code, String country, Set<BankAccountEntity> bankAccountEntities) {
       this.code = code;
       this.country = country;
       this.bankAccountEntities = bankAccountEntities;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="code", unique=true, nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="country", nullable=false, length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy= "currenciesEntity")
    public Set<BankAccountEntity> getBankAccountEntities() {
        return this.bankAccountEntities;
    }
    
    public void setBankAccountEntities(Set<BankAccountEntity> bankAccountEntities) {
        this.bankAccountEntities = bankAccountEntities;
    }




}


