package uk.co.platitech;
// Generated 26-Nov-2014 12:12:14 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccountTransactions generated by hbm2java
 */
@Entity
@Table(name="account_transactions"
    ,catalog="budget_app"
)
public class AccountTransactionsEntity implements java.io.Serializable {


     private String transactionId;
     private TransactionCategoryEntity transactionCategory;
     private BankAccountEntity bankAccount;
     private BudgetsEntity budgetEnty;
     private String transactionAmount;
     private String transactionDate;
     private String transactionName;

    public AccountTransactionsEntity() {
    }

	
    public AccountTransactionsEntity(String transactionId) {
        this.transactionId = transactionId;
    }
    public AccountTransactionsEntity(String transactionId, TransactionCategoryEntity transactionCategory, BankAccountEntity bankAccount, BudgetsEntity budgetEnty, String transactionAmount, String transactionDate, String transactionName) {
       this.transactionId = transactionId;
       this.transactionCategory = transactionCategory;
       this.bankAccount = bankAccount;
       this.budgetEnty = budgetEnty;
       this.transactionAmount = transactionAmount;
       this.transactionDate = transactionDate;
       this.transactionName = transactionName;
    }
   
     @Id 

    
    @Column(name="transaction_id", unique=true, nullable=false)
    public String getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="transaction_type")
    public TransactionCategoryEntity getTransactionCategory() {
        return this.transactionCategory;
    }
    
    public void setTransactionCategory(TransactionCategoryEntity transactionCategory) {
        this.transactionCategory = transactionCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="account")
    public BankAccountEntity getBankAccount() {
        return this.bankAccount;
    }
    
    public void setBankAccount(BankAccountEntity bankAccount) {
        this.bankAccount = bankAccount;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="budget")
    public BudgetsEntity getBudgetEnty() {
        return this.budgetEnty;
    }
    
    public void setBudgetEnty(BudgetsEntity budgets) {
        this.budgetEnty = budgets;
    }

    
    @Column(name="transaction_amount")
    public String getTransactionAmount() {
        return this.transactionAmount;
    }
    
    public void setTransactionAmount(String transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    
    @Column(name="transaction_date")
    public String getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(String transactionDate) {
        this.transactionDate = transactionDate;
    }

    
    @Column(name="transaction_name")
    public String getTransactionName() {
        return this.transactionName;
    }
    
    public void setTransactionName(String transactionName) {
        this.transactionName = transactionName;
    }




}


